server:
    servlet:
        context-path: /
    port: 8082

spring:
    application:
        name: brique-test
    http:
        encoding:
            enabled: true
            force: true
            charset: UTF-8
    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp
    # jdbc
    datasource:
        driverClassName: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://codingtest.brique.kr:3306/employees?characterEncoding=utf8&serverTimezone=UTC
        username: codingtest
        password: 12brique!@
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
        properties:
            hibernate:
                format_sql: true

logging:
    level:
        org:
            hibernate: info